# -*- coding: utf-8 -*-
"""
Created on Sat Sep 23 19:58:42 2017

@author: njhal
"""

healthcaredict =\
{'Don Young': 1,
'Terri A. Sewell': 0,
'Gary J. Palmer': 1,
'Bradley Byrne': 1,
'Mike Rogers': 1,
'Martha Roby': 1,
'Mo Brooks': 1,
'Robert B. Aderholt': 1,
'Bruce Westerman': 1,
'Steve Womack': 1,
'J. French Hill': 1,
'Eric A. "Rick" Crawford': 1,
'Kyrsten Sinema': 0,
'Trent Franks': 1,
'Andy Biggs': 1,
'Paul A. Gosar': 1,
'Ruben Gallego': 0,
'David Schweikert': 1,
"Tom O'Halleran": 0,
'Raul M. Grijalva': 0,
'Martha McSally': 1,
'Jared Huffman': 0,
'Doug LaMalfa': 1,
'Tom McClintock': 1,
'John Garamendi': 0,
'Doris O. Matsui': 0,
'Mike Thompson': 0,
'Paul Cook': 1,
'Ami Bera': 0,
'Jerry McNerney': 0,
'Mark DeSaulnier': 0,
'Jeff Denham': 1,
'Barbara Lee': 0,
'Nancy Pelosi': 0,
'Eric Swalwell': 0,
'Jackie Speier': 0,
'Ro Khanna': 0,
'Jim Costa': 0,
'Zoe Lofgren': 0,
'Anna G. Eshoo': 0,
'Devin Nunes': 1,
'David G. Valadao': 1,
'Salud O. Carbajal': 0,
'Kevin McCarthy': 1,
'Julia Brownley': 0,
'Stephen Knight': 1,
'Adam B. Schiff': 0,
'Judy Chu': 0,
'Jimmy Panetta': 0,
'Juan Vargas': 0,
'Duncan Hunter': 1,
'Susan A. Davis': 0,
'Scott H. Peters': 0,
'Tony Cardenas': 0,
'Ted Lieu': 0,
'Grace F. Napolitano': 0,
'Norma J. Torres': 0,
'Jimmy Gomez': 0,
'Karen Bass': 0,
'Raul Ruiz': 0,
'Edward R. Royce': 1,
'Linda T. Sanchez': 0,
'Pete Aguilar': 0,
'Brad Sherman': 0,
'Nanette Diaz Barragan': 0,
'Maxine Waters': 0,
'J. Luis Correa': 0,
'Mimi Walters': 1,
'Dana Rohrabacher': 1,
'Alan S. Lowenthal': 0,
'Darrell E. Issa': 1,
'Lucille Roybal-Allard': 0,
'Ken Calvert': 1,
'Mark Takano': 0,
'Ed Perlmutter': 0,
'Scott R. Tipton': 1,
'Ken Buck': 1,
'Doug Lamborn': 1,
'Mike Coffman': 1,
'Diana DeGette': 0,
'Jared Polis': 0,
'John B. Larson': 0,
'Rosa L. DeLauro': 0,
'Joe Courtney': 0,
'Elizabeth H. Esty': 0,
'James A. Himes': 0,
'Lisa Blunt Rochester': 0,
'Neal P. Dunn': 1,
'Matt Gaetz': 1,
'John H. Rutherford': 1,
'Ted S. Yoho': 1,
'Ron DeSantis': 1,
'Al Lawson Jr.': 0,
'Bill Posey': 1,
'Stephanie N. Murphy': 0,
'Darren Soto': 0,
'Alcee L. Hastings': 0,
'Daniel Webster': 1,
'Val Butler Demings': 0,
'Charlie Crist': 0,
'Gus M. Bilirakis': 1,
'Dennis A. Ross': 1,
'Kathy Castor': 0,
'Thomas J. Rooney': 1,
'Vern Buchanan': 1,
'Francis Rooney': 1,
'Brian J. Mast': 1,
'Theodore E. Deutch': 0,
'Lois Frankel': 0,
'Frederica S. Wilson': 0,
'Debbie Wasserman Schultz': 0,
'Carlos Curbelo': 1,
'Mario Diaz-Balart': 1,
'Ileana Ros-Lehtinen': 1,
'Tom Graves': 1,
'Rick W. Allen': 1,
'David Scott': 0,
'Jody B. Hice': 1,
'Barry Loudermilk': 1,
'Rob Woodall': 1,
'Austin Scott': 1,
'John Lewis': 0,
'Karen C. Handel': 1,
'Doug Collins': 1,
'A. Drew Ferguson IV': 1,
'Henry C. "Hank" Johnson Jr.': 0,
'Earl L. "Buddy" Carter': 1,
'Sanford D. Bishop Jr.': 0,
'Tulsi Gabbard': 0,
'Colleen Hanabusa': 0,
'David Young': 1,
'Steve King': 1,
'Rod Blum': 1,
'David Loebsack': 0,
'Michael K. Simpson': 1,
'Raul R. Labrador': 1,
'Darin LaHood': 1,
'Cheri Bustos': 0,
'Randy Hultgren': 1,
'Rodney Davis': 1,
'Adam Kinzinger': 1,
'John Shimkus': 1,
'Bradley Scott Schneider': 0,
'Mike Bost': 1,
'Bill Foster': 0,
'Bobby L. Rush': 0,
'Mike Quigley': 0,
'Luis V. Gutierrez': 0,
'Daniel Lipinski': 0,
'Robin L. Kelly': 0,
'Janice D. Schakowsky': 0,
'Raja Krishnamoorthi': 0,
'Danny K. Davis': 0,
'Peter J. Roskam': 1,
'Trey Hollingsworth': 1,
'Larry Bucshon': 1,
'Susan W. Brooks': 1,
'Todd Rokita': 1,
'Andre Carson': 0,
'Luke Messer': 1,
'Peter J. Visclosky': 0,
'Jim Banks': 1,
'Jackie Walorski': 1,
'Roger W. Marshall': 1,
'Lynn Jenkins': 1,
'Kevin Yoder': 1,
'Ron Estes': 1,
'Andy Barr': 1,
'Harold Rogers': 1,
'Thomas Massie': 1,
'John A. Yarmuth': 0,
'Brett Guthrie': 1,
'James Comer': 1,
'Steve Scalise': 1,
'Clay Higgins': 1,
'Cedric L. Richmond': 0,
'Ralph Lee Abraham': 1,
'Mike Johnson': 1,
'Garret Graves': 1,
'Seth Moulton': 0,
'Katherine M. Clark': 0,
'Joseph P. Kennedy III': 0,
'Niki Tsongas': 0,
'James P. McGovern': 0,
'Richard E. Neal': 0,
'William R. Keating': 0,
'Stephen F. Lynch': 0,
'Michael E. Capuano': 0,
'Elijah E. Cummings': 0,
'John K. Delaney': 0,
'Jamie Raskin': 0,
'John P. Sarbanes': 0,
'C. A. Dutch Ruppersberger': 0,
'Steny H. Hoyer': 0,
'Anthony G. Brown': 0,
'Andy Harris': 1,
'Chellie Pingree': 0,
'Bruce Poliquin': 1,
'Sander M. Levin': 0,
'Tim Walberg': 1,
'Mike Bishop': 1,
'Daniel T. Kildee': 0,
'Fred Upton': 1,
'Justin Amash': 1,
'John R. Moolenaar': 1,
'Jack Bergman': 1,
'Bill Huizenga': 1,
'David A. Trott': 1,
'Paul Mitchell': 1,
'Brenda L. Lawrence': 0,
'John Conyers Jr.': 0,
'Debbie Dingell': 0,
'Jason Lewis': 1,
'Erik Paulsen': 1,
'Timothy J. Walz': 0,
'Richard M. Nolan': 0,
'Tom Emmer': 1,
'Collin C. Peterson': 1,
'Betty McCollum': 0,
'Keith Ellison': 0,
'Jason Smith': 1,
'Billy Long': 1,
'Sam Graves': 1,
'Emanuel Cleaver': 0,
'Vicky Hartzler': 1,
'Blaine Luetkemeyer': 1,
'Ann Wagner': 1,
'Wm. Lacy Clay': 0,
'Gregg Harper': 1,
'Steven M. Palazzo': 1,
'Trent Kelly': 1,
'Bennie G. Thompson': 0,
'Greg Gianforte': 1,
'Patrick T. McHenry': 1,
'Ted Budd': 1,
'Alma S. Adams': 0,
'Mark Meadows': 1,
'David Rouzer': 1,
'Mark Walker': 1,
'Virginia Foxx': 1,
'David E. Price': 0,
'Walter B. Jones': 1,
'George Holding': 1,
'G. K. Butterfield': 0,
'Robert Pittenger': 1,
'Richard Hudson': 1,
'Kevin Cramer': 1,
'Jeff Fortenberry': 1,
'Adrian Smith': 1,
'Don Bacon': 1,
'Ann M. Kuster': 0,
'Carol Shea-Porter': 0,
'Bonnie Watson Coleman': 0,
'Donald M. Payne Jr.': 0,
'Rodney P. Frelinghuysen': 1,
'Frank A. LoBiondo': 1,
'Donald Norcross': 0,
'Christopher H. Smith': 1,
'Thomas MacArthur': 1,
'Frank Pallone Jr.': 0,
'Josh Gottheimer': 0,
'Albio Sires': 0,
'Leonard Lance': 1,
'Bill Pascrell Jr.': 0,
'Michelle Lujan Grisham': 0,
'Ben Ray Lujan': 0,
'Stevan Pearce': 1,
'Ruben J. Kihuen': 0,
'Jacky Rosen': 0,
'Mark E. Amodei': 1,
'Dina Titus': 0,
'Nydia M. Velazquez': 0,
'Grace Meng': 0,
'Yvette D. Clarke': 0,
'Hakeem S. Jeffries': 0,
'Lee M. Zeldin': 1,
'Thomas R. Suozzi': 0,
'Peter T. King': 1,
'Gregory W. Meeks': 0,
'Kathleen M. Rice': 0,
'Nita M. Lowey': 0,
'Sean Patrick Maloney': 0,
'John J. Faso': 1,
'Adriano Espaillat': 0,
'Joseph Crowley': 0,
'Jose E. Serrano': 0,
'Eliot L. Engel': 0,
'Jerrold Nadler': 0,
'Daniel M. Donovan Jr.': 1,
'Carolyn B. Maloney': 0,
'John Katko': 1,
'Louise McIntosh Slaughter': 0,
'Brian Higgins': 0,
'Chris Collins': 1,
'Paul Tonko': 0,
'Elise M. Stefanik': 1,
'Claudia Tenney': 1,
'Tom Reed': 1,
'Frank D. Lucas': 1,
'Tom Cole': 1,
'Steve Russell': 1,
'Jim Bridenstine': 1,
'Markwayne Mullin': 1,
'Peter A. DeFazio': 0,
'Kurt Schrader': 0,
'Greg Walden': 1,
'Earl Blumenauer': 0,
'Suzanne Bonamici': 0,
'James R. Langevin': 0,
'David N. Cicilline': 0,
'Mark Sanford': 1,
'Joe Wilson': 1,
'Tom Rice': 1,
'Ralph Norman': 1,
'James E. Clyburn': 0,
'Jeff Duncan': 1,
'Trey Gowdy': 1,
'Kristi L. Noem': 1,
'Marsha Blackburn': 1,
'David Kustoff': 1,
'Jim Cooper': 0,
'Diane Black': 1,
'Steve Cohen': 0,
'Charles J. "Chuck" Fleischmann': 1,
'Scott DesJarlais': 1,
'David P. Roe': 1,
'John J. Duncan Jr.': 1,
'Lloyd Doggett': 0,
'Filemon Vela': 0,
'Brian Babin': 1,
'Henry Cuellar': 0,
'Blake Farenthold': 1,
'Gene Green': 0,
'Kenny Marchant': 1,
'Will Hurd': 1,
'Michael C. Burgess': 1,
'Roger Williams': 1,
'John R. Carter': 1,
'Eddie Bernice Johnson': 0,
'Marc A. Veasey': 0,
'Pete Sessions': 1,
'Bill Flores': 1,
"Beto O'Rourke": 0,
'Jodey C. Arrington': 1,
'Sheila Jackson Lee': 0,
'Mac Thornberry': 1,
'Kay Granger': 1,
'Vicente Gonzalez': 0,
'Randy K. Weber Sr.': 1,
'Joaquin Castro': 0,
'Pete Olson': 1,
'Lamar Smith': 1,
'K. Michael Conaway': 1,
'Michael T. McCaul': 1,
'Louie Gohmert': 1,
'Ted Poe': 1,
'Jeb Hensarling': 1,
'Joe Barton': 1,
'Sam Johnson': 1,
'John Ratcliffe': 1,
'Al Green': 0,
'John Abney Culberson': 1,
'Kevin Brady': 1,
'Rob Bishop': 1,
'Vacant': 0,
'Chris Stewart': 1,
'Mia B. Love': 1,
'Thomas A. Garrett Jr.': 1,
'A. Donald McEachin': 0,
'Robert C. "Bobby" Scott': 0,
'Scott Taylor': 1,
'Robert J. Wittman': 1,
'H. Morgan Griffith': 1,
'Donald S. Beyer Jr.': 0,
'Dave Brat': 1,
'Bob Goodlatte': 1,
'Barbara Comstock': 1,
'Gerald E. Connolly': 0,
'Peter Welch': 0,
'Denny Heck': 0,
'Adam Smith': 0,
'Derek Kilmer': 0,
'Cathy McMorris Rodgers': 1,
'David G. Reichert': 1,
'Pramila Jayapal': 0,
'Rick Larsen': 0,
'Suzan K. DelBene': 0,
'Dan Newhouse': 1,
'Jaime Herrera Beutler': 1,
'F. James Sensenbrenner Jr.': 1,
'Glenn Grothman': 1,
'Sean P. Duffy': 1,
'Mike Gallagher': 1,
'Paul D. Ryan': 1,
'Mark Pocan': 0,
'Ron Kind': 0,
'Gwen Moore': 0,
'Evan H. Jenkins': 1,
'Alexander X. Mooney': 1,
'David B. McKinley': 1,
'Liz Cheney': 1,
'Steve Chabot': 1,
'Brad R. Wenstrup': 1,
'Joyce Beatty': 0,
'Jim Jordan': 1,
'Robert E. Latta': 1,
'Bill Johnson': 1,
'Bob Gibbs': 1,
'Warren Davidson': 1,
'Marcy Kaptur': 0,
'Michael R. Turner': 1,
'Marcia L. Fudge': 0,
'Patrick J. Tiberi': 1,
'Tim Ryan': 0,
'David P. Joyce': 1,
'Steve Stivers': 1,
'James B. Renacci': 1,
'Robert A. Brady': 0,
'Dwight Evans': 0,
'Mike Kelly': 1,
'Scott Perry': 1,
'Glenn Thompson': 1,
'Ryan A. Costello': 1,
'Patrick Meehan': 1,
'Brian K. Fitzpatrick': 1,
'Bill Shuster': 1,
'Tom Marino': 1,
'Lou Barletta': 1,
'Keith J. Rothfus': 1,
'Brendan F. Boyle': 0,
'Michael F. Doyle': 0,
'Charles W. Dent': 1,
'Lloyd Smucker': 1,
'Matt Cartwright': 0,
'Tim Murphy': 1,
}